# Generated by Django 5.2.3 on 2025-06-18 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegisterAndAutor', '0002_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
